### ISSUE TITLE
Integrate UX into the application

### ISSUE THREAD

**Issue by shilojones** [statbid/shopping-feed-analyzer#1]
Here is how the UX is looking so far.
![Desktop Screenshot 2024 10 03 - 16 50 23 55](https://github.com/user-attachments/assets/e78f8b08-b7bb-4042-9b24-93a036034c37)
![Desktop Screenshot 2024 10 03 - 16 51 37 98](https://github.com/user-attachments/assets/dadf83c2-f455-4a7e-9b3b-b26c33df0bac)
![Desktop Screenshot 2024 10 03 - 16 51 47 60](https://github.com/user-attachments/assets/16b80391-9e14-4939-9dd8-d1b862d49508)

**Comment by artemiystlr** [comment]
The Shopping Feed Analyser is coming along great. However, there are certain things that we need to address.

* The font used for the page should be Lato - https://fonts.google.com/specimen/Lato. 

* Scrollbars should be inside of the “Detailed Errors”, not overlapping the background.

* The separators are 2 pixels in height. Hex color is “E4E4E4”

* The height of the upload and analyse buttons should match that of the the file selector. 

* “Learn more…” section should be like this:

Learn more about the 
Shopping Feed Analyser

These are just some things off the top of my head. I will also add more details today.

**Comment by artemiystlr** [comment]
Here are some new revised suggestions:
![SFA_improvements](https://github.com/user-attachments/assets/95d98918-d6a4-479d-88eb-c9e41c789c6a)

**Comment by DGuzmanRomano** [comment]
@artemiystlr  here is the new UX following the suggestions

![UX_r](https://github.com/user-attachments/assets/d23f4a40-1322-4eb8-9bd3-95d5fb216166)

**Comment by artemiystlr** [comment]
That's really great @DGuzmanRomano. Could you please change the background colour for title bars (like "Results", "Best Practise") to #F0F0F0, decrease the font sizes for "Best Practise", "Problem Count" and "How to Fix"?

The results bar is much better now. I also apologize for not being more clear about the "Results" font. It doesn't need a background, please revert to the previous design, add back the separators.

Please make it a bit closer to the design I showed above like this:

> ![results](https://private-user-images.githubusercontent.com/167144767/373633712-228b97fb-e39b-434e-9dae-17961b006cc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTA3MzgsIm5iZiI6MTczMDA1MDQzOCwicGF0aCI6Ii8xNjcxNDQ3NjcvMzczNjMzNzEyLTIyOGI5N2ZiLWUzOWItNDM0ZS05ZGFlLTE3OTYxYjAwNmNjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxNzMzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTAwZWQxNjg2ZGE3NzFlMmQ0Zjg2NTNlMWE4N2NlYzEzYzE5ZTE2NWQwYzE0NWEyNTUyMjJlNzhlOGNmMGM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T3XgYs-ZjE35p1OVjETBSKJMLCzaq0xm1WYaXm6OZLA)

Otherwise, this is just all-around great work, once again, thanks!
